### ISSUE TITLE
ValueError: Namespace GtkVnc not available for version 2.0

### ISSUE THREAD

**Issue by greenrd** [feklee/vncdesk#10]
```
$ vncdesk 2
Traceback (most recent call last):
  File "/usr/bin/vncdesk", line 4, in <module>
    __import__('pkg_resources').run_script('vncdesk==1.4.1', 'vncdesk')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/vncdesk-1.4.1-py2.7.egg/EGG-INFO/scripts/vncdesk", line 3, in <module>
    __requires__ = 'vncdesk==1.4.1'
  File "build/bdist.linux-x86_64/egg/vncdesk/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/vncdesk/main.py", line 5, in <module>
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 122, in require_version
    (namespace, version))
ValueError: Namespace GtkVnc not available for version 2.0
```

**Comment by feklee** [comment]
What OS are you using? What is your configuration number 2?

**Comment by feklee** [comment]
Looks like you're running Python 2.7. Please install Python 3, which is listed as requirement for vncdesk.
