### ISSUE TITLE
ImportError: cannot import name quote

### ISSUE THREAD

**Issue by wiredin** [feklee/vncdesk#12]
Hi everyone,

I'm getting `ImportError: cannot import name quote` when trying to run vncdesk on ubuntu, I believe I have all the correct libraries installed..

`chrx@chrx:~$ vncdesk 1`
`Traceback (most recent call last):
  File "/usr/local/bin/vncdesk", line 4, in <module>
    __import__('pkg_resources').run_script('vncdesk==1.6.2', 'vncdesk')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/vncdesk-1.6.2-py2.7.egg/EGG-INFO/scripts/vncdesk", line 3, in <module>
    __requires__ = 'vncdesk==1.6.2'
  File "build/bdist.linux-x86_64/egg/vncdesk/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/vncdesk/main.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/vncdesk/vnc_server.py", line 8, in <module>`
`ImportError: cannot import name quote`

**Comment by wiredin** [comment]
I installed with 
`pip3 install .`
instead of 
`python setup.py install`
and the error is now gone.

I must have been missing a library which pip3 resolved.

**Comment by feklee** [comment]
Thanks for the report, and I'm happy to hear that you solved the issue!
